### ISSUE TITLE
No ligths shown on list

### ISSUE THREAD

**Issue by 7Ds7** [ristomatti/lifxsh#5]
Hello, thank you for developing this :)

Although i do not seem to have any lights listing, they do appear on the official app though.
I tried both a global install and a local install, the light model is LIFX(A19) and i also tried to reset the light itself.

```
~ lifxsh 
LIFX> list
Label Alias Power Hue Sat. Bri. Temp. ID IP 
LIFX> 
```

Any hints as why no lights show up, no errors are thrown.

Maybe you can provide a sample for the settings.yml file so i can replicate with my own manually?

**Comment by ristomatti** [comment]
Sorry for the slow response. There hasn't been too much activity on this repo :slightly_smiling_face:!

It's almost certainly an issue with the network. I recommend to go related issues on the (original fork) of the underlying library: https://github.com/MariusRumpf/node-lifx/issues?q=+network+OR+firewall+. Here's a snippet from my settings.yml anyhow:

```
#
# lifxsh settings
#
lights:
  - 192.168.5.76 # bedside-table
  - 192.168.6.61 # lr-ceiling
```

Let me know if you get it working.

**Comment by 7Ds7** [comment]
Adding the file `~/lifxsh/settings.yml`   with my light IP worked :magic_wand: 

Thank you :smiley:
